### ISSUE TITLE
Decide on emoji to represent the project

### ISSUE THREAD

**Issue by amorriscode** [XifeiNi/jslings#11]
Instead of having a "logo", let's just pick an emoji! Anyone have any preferences? Since we are using ink, I thought of 🐙 but I'm totally open.

**Comment by XifeiNi** [comment]
🐳

**Comment by XifeiNi** [comment]
I thought you preferred 🐢 yesterday lol.

**Comment by amorriscode** [comment]
Haha no preference, just want to discuss as a team! :D
